// ──────────────────────────────────────────────────────────
//  MedNexModelTests.swift
//  MedNexTests
//
//  Comprehensive XCTest unit tests for all MedNex models.
//  Run via Xcode: ⌘+U or Product → Test
// ──────────────────────────────────────────────────────────

import XCTest
@testable import MedNex

// ═══════════════════════════════════════════════════════════
// MARK: - 1. USER & ROLE TESTS
// ═══════════════════════════════════════════════════════════

final class UserRoleTests: XCTestCase {
    
    func testRoleCountIs8() {
        XCTAssertEqual(UserRole.allCases.count, 8)
    }
    
    func testAllRolesHaveNonEmptyDisplayNames() {
        for role in UserRole.allCases {
            XCTAssertFalse(role.displayName.isEmpty, "\(role) displayName is empty")
        }
    }
    
    func testAllRolesHaveNonEmptyIcons() {
        for role in UserRole.allCases {
            XCTAssertFalse(role.icon.isEmpty, "\(role) icon is empty")
        }
    }
    
    func testPatientIsNotStaff() {
        XCTAssertFalse(UserRole.patient.isStaff)
    }
    
    func testDoctorIsStaff() {
        XCTAssertTrue(UserRole.doctor.isStaff)
    }
    
    func testAdminIsStaff() {
        XCTAssertTrue(UserRole.admin.isStaff)
    }
    
    func testNurseIsStaff() {
        XCTAssertTrue(UserRole.nurse.isStaff)
    }
    
    func testLabTechnicianIsStaff() {
        XCTAssertTrue(UserRole.labTechnician.isStaff)
    }
    
    func testPharmacistIsStaff() {
        XCTAssertTrue(UserRole.pharmacist.isStaff)
    }
    
    func testReceptionistIsStaff() {
        XCTAssertTrue(UserRole.receptionist.isStaff)
    }
    
    func testAccountantIsStaff() {
        XCTAssertTrue(UserRole.accountant.isStaff)
    }
    
    func testRoleIdentifiersAreUnique() {
        let ids = UserRole.allCases.map { $0.id }
        XCTAssertEqual(ids.count, Set(ids).count)
    }
    
    func testRoleCodableRawValues() {
        XCTAssertEqual(UserRole.labTechnician.rawValue, "lab_technician")
        XCTAssertEqual(UserRole.patient.rawValue, "patient")
        XCTAssertEqual(UserRole.doctor.rawValue, "doctor")
        XCTAssertEqual(UserRole.admin.rawValue, "admin")
    }
    
    func testDisplayNameCorrectness() {
        XCTAssertEqual(UserRole.labTechnician.displayName, "Lab Technician")
        XCTAssertEqual(UserRole.doctor.displayName, "Doctor")
        XCTAssertEqual(UserRole.patient.displayName, "Patient")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - MedNexUser Tests
// ═══════════════════════════════════════════════════════════

final class MedNexUserTests: XCTestCase {
    
    func testUserCreationWithDefaults() {
        let user = MedNexUser(email: "test@mednex.com", role: .patient, displayName: "Test User")
        XCTAssertEqual(user.email, "test@mednex.com")
        XCTAssertEqual(user.role, .patient)
        XCTAssertEqual(user.displayName, "Test User")
        XCTAssertTrue(user.isActive)
        XCTAssertNil(user.profileImageURL)
        XCTAssertNil(user.phoneNumber)
    }
    
    func testUserAsDoctorWithPhone() {
        let user = MedNexUser(email: "dr@mednex.com", role: .doctor, displayName: "Dr. Smith", phoneNumber: "+91-9999999999")
        XCTAssertEqual(user.role, .doctor)
        XCTAssertNotNil(user.phoneNumber)
    }
    
    func testAutoGeneratedIDsAreUnique() {
        let u1 = MedNexUser(email: "a@b.com", role: .patient, displayName: "A")
        let u2 = MedNexUser(email: "c@d.com", role: .patient, displayName: "B")
        XCTAssertNotEqual(u1.id, u2.id)
    }
    
    func testUserCodableRoundTrip() throws {
        let user = MedNexUser(email: "test@test.com", role: .doctor, displayName: "Dr. X", isActive: false)
        let data = try JSONEncoder().encode(user)
        let decoded = try JSONDecoder().decode(MedNexUser.self, from: data)
        XCTAssertEqual(decoded.email, "test@test.com")
        XCTAssertEqual(decoded.role, .doctor)
        XCTAssertEqual(decoded.displayName, "Dr. X")
        XCTAssertFalse(decoded.isActive)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 2. PATIENT MODEL TESTS
// ═══════════════════════════════════════════════════════════

final class PersonalInfoTests: XCTestCase {
    
    func testFullNameConcatenation() {
        let info = PersonalInfo(firstName: "Rahul", lastName: "Sharma")
        XCTAssertEqual(info.fullName, "Rahul Sharma")
    }
    
    func testFullNameWithEmptyParts() {
        XCTAssertEqual(PersonalInfo().fullName, " ")
    }
    
    func testAgeCalculation25YearsOld() {
        let dob = Calendar.current.date(byAdding: .year, value: -25, to: Date())!
        let info = PersonalInfo(firstName: "A", dateOfBirth: dob)
        XCTAssertEqual(info.age, 25)
    }
    
    func testAgeCalculationNewborn() {
        let info = PersonalInfo(firstName: "Baby", dateOfBirth: Date())
        XCTAssertEqual(info.age, 0)
    }
    
    func testDefaultGenderIsOther() {
        XCTAssertEqual(PersonalInfo().gender, .other)
    }
}

final class GenderTests: XCTestCase {
    
    func testDisplayNamesAreCapitalized() {
        XCTAssertEqual(Gender.male.displayName, "Male")
        XCTAssertEqual(Gender.female.displayName, "Female")
        XCTAssertEqual(Gender.other.displayName, "Other")
    }
    
    func testGenderCountIs3() {
        XCTAssertEqual(Gender.allCases.count, 3)
    }
}

final class BloodTypeTests: XCTestCase {
    
    func test9BloodTypes() {
        XCTAssertEqual(BloodType.allCases.count, 9)
    }
    
    func testRawValuesMatchStandardNotation() {
        XCTAssertEqual(BloodType.aPositive.rawValue, "A+")
        XCTAssertEqual(BloodType.oNegative.rawValue, "O-")
        XCTAssertEqual(BloodType.abPositive.rawValue, "AB+")
        XCTAssertEqual(BloodType.abNegative.rawValue, "AB-")
        XCTAssertEqual(BloodType.unknown.rawValue, "Unknown")
    }
}

final class MedicalInfoTests: XCTestCase {
    
    func testDefaultMedicalInfoIsEmpty() {
        let info = MedicalInfo()
        XCTAssertEqual(info.bloodType, .unknown)
        XCTAssertTrue(info.allergies.isEmpty)
        XCTAssertTrue(info.chronicConditions.isEmpty)
        XCTAssertTrue(info.currentMedications.isEmpty)
        XCTAssertNil(info.height)
        XCTAssertNil(info.weight)
    }
    
    func testCustomMedicalInfo() {
        let info = MedicalInfo(bloodType: .bPositive, allergies: ["Penicillin", "Dust"], height: 175, weight: 70)
        XCTAssertEqual(info.bloodType, .bPositive)
        XCTAssertEqual(info.allergies.count, 2)
        XCTAssertEqual(info.height, 175)
    }
}

final class PatientTests: XCTestCase {
    
    func testPatientCreation() {
        let p = Patient(userId: "user-1", personalInfo: PersonalInfo(firstName: "Priya", lastName: "Mehta"))
        XCTAssertEqual(p.userId, "user-1")
        XCTAssertEqual(p.personalInfo.fullName, "Priya Mehta")
        XCTAssertTrue(p.emergencyContacts.isEmpty)
    }
    
    func testPatientWithEmergencyContacts() {
        let contacts = [EmergencyContact(name: "A", relationship: "Parent", phone: "111")]
        let p = Patient(userId: "u1", personalInfo: PersonalInfo(), emergencyContacts: contacts)
        XCTAssertEqual(p.emergencyContacts.count, 1)
    }
}

final class EmergencyContactTests: XCTestCase {
    
    func testContactCreation() {
        let c = EmergencyContact(name: "Mom", relationship: "Mother", phone: "+91-8888888888")
        XCTAssertEqual(c.name, "Mom")
        XCTAssertEqual(c.relationship, "Mother")
        XCTAssertFalse(c.phone.isEmpty)
    }
    
    func testDefaultContactIsEmpty() {
        let c = EmergencyContact()
        XCTAssertTrue(c.name.isEmpty)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 3. DOCTOR MODEL TESTS
// ═══════════════════════════════════════════════════════════

final class DoctorTests: XCTestCase {
    
    func testDoctorCreationDefaults() {
        let doc = Doctor(name: "Dr. Kumar")
        XCTAssertEqual(doc.name, "Dr. Kumar")
        XCTAssertEqual(doc.specialty, .generalMedicine)
        XCTAssertEqual(doc.consultationFee, 500)
        XCTAssertEqual(doc.rating, 4.5, accuracy: 0.001)
        XCTAssertTrue(doc.isAvailable)
        XCTAssertTrue(doc.availableSlots.isEmpty)
        XCTAssertEqual(doc.totalRatings, 0)
    }
    
    func testDoctorWithSpecialty() {
        let doc = Doctor(name: "Dr. Heart", specialty: .cardiology, experience: 15, consultationFee: 1500)
        XCTAssertEqual(doc.specialty, .cardiology)
        XCTAssertEqual(doc.experience, 15)
        XCTAssertEqual(doc.consultationFee, 1500)
    }
}

final class MedicalSpecialtyTests: XCTestCase {
    
    func test18Specialties() {
        XCTAssertEqual(MedicalSpecialty.allCases.count, 18)
    }
    
    func testAllSpecialtiesHaveNonEmptyIcons() {
        for s in MedicalSpecialty.allCases {
            XCTAssertFalse(s.icon.isEmpty, "\(s) icon empty")
        }
    }
    
    func testIDsAreUnique() {
        let ids = MedicalSpecialty.allCases.map { $0.id }
        XCTAssertEqual(ids.count, Set(ids).count)
    }
    
    func testKnownIconValues() {
        XCTAssertEqual(MedicalSpecialty.cardiology.icon, "heart.fill")
        XCTAssertEqual(MedicalSpecialty.neurology.icon, "brain.head.profile")
        XCTAssertEqual(MedicalSpecialty.ophthalmology.icon, "eye.fill")
        XCTAssertEqual(MedicalSpecialty.pulmonology.icon, "lungs.fill")
    }
    
    func testGeneralMedicineAsDefaultIcon() {
        XCTAssertEqual(MedicalSpecialty.generalMedicine.icon, "stethoscope")
    }
}

final class TimeSlotTests: XCTestCase {
    
    func testDefaultIsNotBooked() {
        XCTAssertFalse(TimeSlot().isBooked)
    }
    
    func testBookedState() {
        XCTAssertTrue(TimeSlot(isBooked: true).isBooked)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 4. APPOINTMENT TESTS
// ═══════════════════════════════════════════════════════════

final class AppointmentTests: XCTestCase {
    
    func testDefaults() {
        let a = Appointment(patientId: "p1", doctorId: "d1")
        XCTAssertEqual(a.status, .scheduled)
        XCTAssertEqual(a.type, .consultation)
        XCTAssertEqual(a.billingStatus, .pending)
        XCTAssertNil(a.cancellationReason)
        XCTAssertNil(a.rating)
        XCTAssertNil(a.review)
    }
    
    func testCanCancelTrue5HoursOut() {
        let date = Calendar.current.date(byAdding: .hour, value: 5, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .scheduled)
        XCTAssertTrue(a.canCancel)
    }
    
    func testCanCancelFalse2HoursOut() {
        let date = Calendar.current.date(byAdding: .hour, value: 2, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .scheduled)
        XCTAssertFalse(a.canCancel)
    }
    
    func testCanCancelFalseCompleted() {
        let date = Calendar.current.date(byAdding: .hour, value: 10, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .completed)
        XCTAssertFalse(a.canCancel)
    }
    
    func testCanCancelFalseCancelled() {
        let date = Calendar.current.date(byAdding: .hour, value: 10, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .cancelled)
        XCTAssertFalse(a.canCancel)
    }
    
    func testCanCancelFalseInProgress() {
        let date = Calendar.current.date(byAdding: .hour, value: 10, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .inProgress)
        XCTAssertFalse(a.canCancel)
    }
    
    func testCanCancelFalsePastDate() {
        let date = Calendar.current.date(byAdding: .day, value: -1, to: Date())!
        let a = Appointment(patientId: "p1", doctorId: "d1", dateTime: date, status: .scheduled)
        XCTAssertFalse(a.canCancel)
    }
}

final class AppointmentStatusTests: XCTestCase {
    
    func test5Statuses() {
        XCTAssertEqual(AppointmentStatus.allCases.count, 5)
    }
    
    func testAllHaveDisplayNames() {
        for s in AppointmentStatus.allCases { XCTAssertFalse(s.displayName.isEmpty) }
    }
    
    func testAllHaveColorHexCodes() {
        for s in AppointmentStatus.allCases { XCTAssertEqual(s.color.count, 6) }
    }
    
    func testDisplayNameValues() {
        XCTAssertEqual(AppointmentStatus.scheduled.displayName, "Scheduled")
        XCTAssertEqual(AppointmentStatus.inProgress.displayName, "In Progress")
        XCTAssertEqual(AppointmentStatus.completed.displayName, "Completed")
        XCTAssertEqual(AppointmentStatus.cancelled.displayName, "Cancelled")
        XCTAssertEqual(AppointmentStatus.noShow.displayName, "No Show")
    }
    
    func testCodableRawValues() {
        XCTAssertEqual(AppointmentStatus.inProgress.rawValue, "in_progress")
        XCTAssertEqual(AppointmentStatus.noShow.rawValue, "no_show")
    }
}

final class AppointmentTypeTests: XCTestCase {
    
    func test5Types() {
        XCTAssertEqual(AppointmentType.allCases.count, 5)
    }
    
    func testDisplayNames() {
        XCTAssertEqual(AppointmentType.followUp.displayName, "Follow-up")
        XCTAssertEqual(AppointmentType.emergency.displayName, "Emergency")
        XCTAssertEqual(AppointmentType.consultation.displayName, "Consultation")
    }
    
    func testFollowUpRawValue() {
        XCTAssertEqual(AppointmentType.followUp.rawValue, "follow_up")
    }
}

final class BillingStatusTests: XCTestCase {
    
    func testDisplayNames() {
        XCTAssertEqual(BillingStatus.pending.displayName, "Pending")
        XCTAssertEqual(BillingStatus.partiallyPaid.displayName, "Partially Paid")
        XCTAssertEqual(BillingStatus.paid.displayName, "Paid")
    }
    
    func testRawValue() {
        XCTAssertEqual(BillingStatus.partiallyPaid.rawValue, "partially_paid")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 5. BILL TESTS
// ═══════════════════════════════════════════════════════════

final class BillTests: XCTestCase {
    
    func testBalanceDue() {
        let b = Bill(patientId: "p1", totalAmount: 1000, paidAmount: 300)
        XCTAssertEqual(b.balanceDue, 700, accuracy: 0.001)
    }
    
    func testZeroBalanceWhenFullyPaid() {
        let b = Bill(patientId: "p1", totalAmount: 500, paidAmount: 500)
        XCTAssertEqual(b.balanceDue, 0, accuracy: 0.001)
    }
    
    func testFullBalanceWhenUnpaid() {
        let b = Bill(patientId: "p1", totalAmount: 2000, paidAmount: 0)
        XCTAssertEqual(b.balanceDue, 2000, accuracy: 0.001)
    }
    
    func testNegativeBalanceOverpaid() {
        let b = Bill(patientId: "p1", totalAmount: 100, paidAmount: 150)
        XCTAssertEqual(b.balanceDue, -50, accuracy: 0.001)
    }
    
    func testDefaultStatusIsUnpaid() {
        XCTAssertEqual(Bill(patientId: "p1").status, .unpaid)
    }
    
    func testBillCodableRoundTrip() throws {
        let b = Bill(patientId: "p1", patientName: "Test", totalAmount: 1500, paidAmount: 500, status: .partial)
        let data = try JSONEncoder().encode(b)
        let decoded = try JSONDecoder().decode(Bill.self, from: data)
        XCTAssertEqual(decoded.totalAmount, 1500, accuracy: 0.001)
        XCTAssertEqual(decoded.paidAmount, 500, accuracy: 0.001)
        XCTAssertEqual(decoded.status, .partial)
    }
}

final class BillItemTests: XCTestCase {
    
    func testItemCreation() {
        let i = BillItem(description: "Consultation", quantity: 1, unitPrice: 500, total: 500, category: .consultation)
        XCTAssertEqual(i.description, "Consultation")
        XCTAssertEqual(i.quantity, 1)
        XCTAssertEqual(i.total, 500, accuracy: 0.001)
    }
    
    func testDefaults() {
        let i = BillItem()
        XCTAssertEqual(i.quantity, 1)
        XCTAssertEqual(i.unitPrice, 0, accuracy: 0.001)
    }
}

final class BillStatusTests: XCTestCase {
    
    func test5BillStatuses() {
        XCTAssertEqual(BillStatus.allCases.count, 5)
    }
    
    func testAllHaveDisplayNamesAndColors() {
        for s in BillStatus.allCases {
            XCTAssertFalse(s.displayName.isEmpty)
            XCTAssertFalse(s.color.isEmpty)
        }
    }
}

final class BillItemCategoryTests: XCTestCase {
    
    func test6Categories() {
        XCTAssertEqual(BillItemCategory.allCases.count, 6)
    }
    
    func testAllHaveDisplayNames() {
        for c in BillItemCategory.allCases { XCTAssertFalse(c.displayName.isEmpty) }
    }
    
    func testLabTestRawValue() {
        XCTAssertEqual(BillItemCategory.labTest.rawValue, "lab_test")
        XCTAssertEqual(BillItemCategory.roomCharge.rawValue, "room_charge")
    }
}

final class PaymentModeTests: XCTestCase {
    
    func test5PaymentModes() {
        XCTAssertEqual(PaymentMode.allCases.count, 5)
    }
    
    func testAllHaveDisplayNames() {
        for m in PaymentMode.allCases { XCTAssertFalse(m.displayName.isEmpty) }
    }
    
    func testBankTransferRawValue() {
        XCTAssertEqual(PaymentMode.bankTransfer.rawValue, "bank_transfer")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 6. PRESCRIPTION TESTS
// ═══════════════════════════════════════════════════════════

final class PrescriptionTests: XCTestCase {
    
    func testCreationWithMedicines() {
        let rx = Prescription(
            appointmentId: "a1", patientId: "p1", patientName: "Patient",
            doctorId: "d1", doctorName: "Dr. Test",
            medicines: [PrescribedMedicine(name: "Paracetamol", dosage: "500mg")],
            diagnosis: "Fever"
        )
        XCTAssertEqual(rx.diagnosis, "Fever")
        XCTAssertEqual(rx.medicines.count, 1)
        XCTAssertEqual(rx.status, .active)
    }
    
    func testDefaultStatusIsActive() {
        let rx = Prescription(patientId: "p1", doctorId: "d1")
        XCTAssertEqual(rx.status, .active)
    }
    
    func testCodableRoundTrip() throws {
        let med = PrescribedMedicine(name: "Ibuprofen", dosage: "400mg", frequency: .twiceDaily)
        let rx = Prescription(appointmentId: "a1", patientId: "p1", patientName: "P", doctorId: "d1", doctorName: "D", medicines: [med], diagnosis: "Pain")
        let data = try JSONEncoder().encode(rx)
        let decoded = try JSONDecoder().decode(Prescription.self, from: data)
        XCTAssertEqual(decoded.diagnosis, "Pain")
        XCTAssertEqual(decoded.medicines.first?.name, "Ibuprofen")
    }
}

final class PrescribedMedicineTests: XCTestCase {
    
    func testMedicineCreation() {
        let m = PrescribedMedicine(name: "Amoxicillin", dosage: "250mg", frequency: .twiceDaily, duration: "7 days", instructions: "After meals")
        XCTAssertEqual(m.name, "Amoxicillin")
        XCTAssertEqual(m.frequency, .twiceDaily)
        XCTAssertFalse(m.isTaken)
    }
    
    func testDefaultFrequencyIsOnceDaily() {
        XCTAssertEqual(PrescribedMedicine().frequency, .onceDaily)
    }
    
    func testDefaultIsTakenIsFalse() {
        XCTAssertFalse(PrescribedMedicine().isTaken)
    }
}

final class PrescriptionStatusTests: XCTestCase {
    
    func testDisplayNames() {
        XCTAssertEqual(PrescriptionStatus.active.displayName, "Active")
        XCTAssertEqual(PrescriptionStatus.completed.displayName, "Completed")
        XCTAssertEqual(PrescriptionStatus.dispensed.displayName, "Dispensed")
        XCTAssertEqual(PrescriptionStatus.partiallyDispensed.displayName, "Partially Dispensed")
        XCTAssertEqual(PrescriptionStatus.cancelled.displayName, "Cancelled")
    }
    
    func testColorsAreHexCodes() {
        XCTAssertEqual(PrescriptionStatus.active.color.count, 6)
        XCTAssertEqual(PrescriptionStatus.completed.color.count, 6)
    }
    
    func testRawValueForPartiallyDispensed() {
        XCTAssertEqual(PrescriptionStatus.partiallyDispensed.rawValue, "partially_dispensed")
    }
}

final class MedicineFrequencyTests: XCTestCase {
    
    func test9Frequencies() {
        XCTAssertEqual(MedicineFrequency.allCases.count, 9)
    }
    
    func testKnownRawValues() {
        XCTAssertEqual(MedicineFrequency.onceDaily.rawValue, "Once Daily")
        XCTAssertEqual(MedicineFrequency.twiceDaily.rawValue, "Twice Daily")
        XCTAssertEqual(MedicineFrequency.thriceDaily.rawValue, "Thrice Daily")
        XCTAssertEqual(MedicineFrequency.fourTimesDaily.rawValue, "Four Times Daily")
        XCTAssertEqual(MedicineFrequency.asNeeded.rawValue, "As Needed")
        XCTAssertEqual(MedicineFrequency.weekly.rawValue, "Weekly")
        XCTAssertEqual(MedicineFrequency.beforeMeals.rawValue, "Before Meals")
        XCTAssertEqual(MedicineFrequency.afterMeals.rawValue, "After Meals")
        XCTAssertEqual(MedicineFrequency.bedtime.rawValue, "At Bedtime")
    }
}

final class MedicineTests: XCTestCase {
    
    func testMedicineCatalogItemCreation() {
        let m = Medicine(name: "Amoxicillin", genericName: "Amoxicillin Trihydrate", category: "Antibiotic")
        XCTAssertEqual(m.name, "Amoxicillin")
        XCTAssertEqual(m.genericName, "Amoxicillin Trihydrate")
        XCTAssertEqual(m.category, "Antibiotic")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 7. LAB TEST TESTS
// ═══════════════════════════════════════════════════════════

final class LabTestTests: XCTestCase {
    
    func testCreationDefaults() {
        let t = LabTest(patientId: "p1", doctorId: "d1", testName: "CBC", testCategory: .bloodWork)
        XCTAssertEqual(t.testName, "CBC")
        XCTAssertEqual(t.testCategory, .bloodWork)
        XCTAssertEqual(t.status, .pending)
        XCTAssertEqual(t.priority, .routine)
        XCTAssertTrue(t.results.isEmpty)
        XCTAssertNil(t.completedAt)
    }
    
    func testWithAbnormalResults() {
        let r = LabTestResult(parameterName: "WBC", value: "25000", unit: "cells/mcL", normalRange: "4000-11000", isAbnormal: true)
        XCTAssertTrue(r.isAbnormal)
        XCTAssertEqual(r.parameterName, "WBC")
    }
    
    func testWithNormalResults() {
        let r = LabTestResult(parameterName: "Hemoglobin", value: "14.5", unit: "g/dL", normalRange: "12-16", isAbnormal: false)
        XCTAssertFalse(r.isAbnormal)
    }
    
    func testCodableRoundTrip() throws {
        let t = LabTest(patientId: "p1", doctorId: "d1", testName: "Lipid Panel", testCategory: .bloodWork, priority: .urgent)
        let data = try JSONEncoder().encode(t)
        let decoded = try JSONDecoder().decode(LabTest.self, from: data)
        XCTAssertEqual(decoded.testName, "Lipid Panel")
        XCTAssertEqual(decoded.priority, .urgent)
    }
}

final class LabTestStatusTests: XCTestCase {
    
    func test5Statuses() {
        XCTAssertEqual(LabTestStatus.allCases.count, 5)
    }
    
    func testAllHaveDisplayNamesColorsIcons() {
        for s in LabTestStatus.allCases {
            XCTAssertFalse(s.displayName.isEmpty)
            XCTAssertFalse(s.color.isEmpty)
            XCTAssertFalse(s.icon.isEmpty)
        }
    }
    
    func testDisplayNameCapitalized() {
        XCTAssertEqual(LabTestStatus.pending.displayName, "Pending")
        XCTAssertEqual(LabTestStatus.processing.displayName, "Processing")
        XCTAssertEqual(LabTestStatus.completed.displayName, "Completed")
    }
}

final class LabTestCategoryTests: XCTestCase {
    
    func test9Categories() {
        XCTAssertEqual(LabTestCategory.allCases.count, 9)
    }
    
    func testBloodWorkRawValue() {
        XCTAssertEqual(LabTestCategory.bloodWork.rawValue, "Blood Work")
    }
}

final class LabTestPriorityTests: XCTestCase {
    
    func test3Priorities() {
        XCTAssertEqual(LabTestPriority.allCases.count, 3)
    }
    
    func testAllHaveColors() {
        for p in LabTestPriority.allCases { XCTAssertFalse(p.color.isEmpty) }
    }
    
    func testDisplayNames() {
        XCTAssertEqual(LabTestPriority.routine.displayName, "Routine")
        XCTAssertEqual(LabTestPriority.urgent.displayName, "Urgent")
        XCTAssertEqual(LabTestPriority.stat.displayName, "Stat")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 8. VITAL RECORD TESTS
// ═══════════════════════════════════════════════════════════

final class VitalRecordTests: XCTestCase {
    
    func testBloodPressureFormatted() {
        let v = VitalRecord(patientId: "p1", bloodPressureSystolic: 120, bloodPressureDiastolic: 80)
        XCTAssertEqual(v.bloodPressureFormatted, "120/80 mmHg")
    }
    
    func testBloodPressureNilWhenPartialData() {
        XCTAssertNil(VitalRecord(patientId: "p1", bloodPressureSystolic: 120).bloodPressureFormatted)
        XCTAssertNil(VitalRecord(patientId: "p1", bloodPressureDiastolic: 80).bloodPressureFormatted)
    }
    
    func testHeartRateFormatted() {
        XCTAssertEqual(VitalRecord(patientId: "p1", heartRate: 72).heartRateFormatted, "72 bpm")
    }
    
    func testHeartRateNilWhenMissing() {
        XCTAssertNil(VitalRecord(patientId: "p1").heartRateFormatted)
    }
    
    func testTemperatureFormatted() {
        XCTAssertEqual(VitalRecord(patientId: "p1", temperature: 98.6).temperatureFormatted, "98.6°F")
    }
    
    func testSpO2Formatted() {
        XCTAssertEqual(VitalRecord(patientId: "p1", oxygenSaturation: 98).spO2Formatted, "98%")
    }
    
    func testSpO2NilWhenMissing() {
        XCTAssertNil(VitalRecord(patientId: "p1").spO2Formatted)
    }
    
    func testAllVitalsNilByDefault() {
        let v = VitalRecord(patientId: "p1")
        XCTAssertNil(v.bloodPressureSystolic)
        XCTAssertNil(v.heartRate)
        XCTAssertNil(v.temperature)
        XCTAssertNil(v.oxygenSaturation)
        XCTAssertNil(v.bloodGlucose)
        XCTAssertNil(v.weight)
        XCTAssertNil(v.height)
    }
    
    func testAllVitalsPopulated() {
        let v = VitalRecord(patientId: "p1", bloodPressureSystolic: 130, bloodPressureDiastolic: 85,
                            heartRate: 90, temperature: 101.2, oxygenSaturation: 95)
        XCTAssertNotNil(v.bloodPressureFormatted)
        XCTAssertNotNil(v.heartRateFormatted)
        XCTAssertNotNil(v.temperatureFormatted)
        XCTAssertNotNil(v.spO2Formatted)
    }
    
    func testCodableRoundTrip() throws {
        let v = VitalRecord(patientId: "p1", bloodPressureSystolic: 120, bloodPressureDiastolic: 80, heartRate: 72)
        let data = try JSONEncoder().encode(v)
        let decoded = try JSONDecoder().decode(VitalRecord.self, from: data)
        XCTAssertEqual(decoded.bloodPressureFormatted, "120/80 mmHg")
        XCTAssertEqual(decoded.heartRateFormatted, "72 bpm")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 9. INVENTORY TESTS
// ═══════════════════════════════════════════════════════════

final class InventoryItemTests: XCTestCase {
    
    func testLowStockAtReorderLevel() {
        XCTAssertTrue(InventoryItem(name: "A", stock: 10, reorderLevel: 10).isLowStock)
    }
    
    func testLowStockBelowReorderLevel() {
        XCTAssertTrue(InventoryItem(name: "A", stock: 5, reorderLevel: 10).isLowStock)
    }
    
    func testLowStockZeroStock() {
        XCTAssertTrue(InventoryItem(name: "A", stock: 0, reorderLevel: 10).isLowStock)
    }
    
    func testNotLowStockAboveReorderLevel() {
        XCTAssertFalse(InventoryItem(name: "A", stock: 100, reorderLevel: 10).isLowStock)
    }
    
    func testDefaultCategoryIsMedication() {
        XCTAssertEqual(InventoryItem(name: "Test").category, .medication)
    }
    
    func testCodableRoundTrip() throws {
        let i = InventoryItem(name: "Gloves", category: .consumables, stock: 500, reorderLevel: 50)
        let data = try JSONEncoder().encode(i)
        let decoded = try JSONDecoder().decode(InventoryItem.self, from: data)
        XCTAssertEqual(decoded.name, "Gloves")
        XCTAssertEqual(decoded.category, .consumables)
        XCTAssertFalse(decoded.isLowStock)
    }
}

final class InventoryCategoryTests: XCTestCase {
    
    func test6Categories() {
        XCTAssertEqual(InventoryCategory.allCases.count, 6)
    }
    
    func testLabSuppliesRawValue() {
        XCTAssertEqual(InventoryCategory.labSupplies.rawValue, "Lab Supplies")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 10. ADMISSION TESTS
// ═══════════════════════════════════════════════════════════

final class AdmissionTests: XCTestCase {
    
    func testDefaultStatusIsAdmitted() {
        let a = Admission(patientId: "p1")
        XCTAssertEqual(a.status, .admitted)
        XCTAssertTrue(a.doctorIds.isEmpty)
        XCTAssertNil(a.dischargeDate)
        XCTAssertEqual(a.dailyRoomRate, 0, accuracy: 0.001)
    }
    
    func testWithDetails() {
        let a = Admission(patientId: "p1", doctorIds: ["d1", "d2"], bedNumber: "ICU-01", dailyRoomRate: 5000)
        XCTAssertEqual(a.doctorIds.count, 2)
        XCTAssertEqual(a.bedNumber, "ICU-01")
    }
    
    func testCodableRoundTrip() throws {
        let a = Admission(patientId: "p1", doctorIds: ["d1"], status: .discharged)
        let data = try JSONEncoder().encode(a)
        let decoded = try JSONDecoder().decode(Admission.self, from: data)
        XCTAssertEqual(decoded.status, .discharged)
        XCTAssertEqual(decoded.doctorIds.count, 1)
    }
}

final class AdmissionStatusTests: XCTestCase {
    
    func test3Statuses() {
        XCTAssertEqual(AdmissionStatus.allCases.count, 3)
    }
    
    func testAllHaveDisplayNamesColorsIcons() {
        for s in AdmissionStatus.allCases {
            XCTAssertFalse(s.displayName.isEmpty)
            XCTAssertFalse(s.color.isEmpty)
            XCTAssertFalse(s.icon.isEmpty)
        }
    }
    
    func testDisplayNamesCapitalized() {
        XCTAssertEqual(AdmissionStatus.admitted.displayName, "Admitted")
        XCTAssertEqual(AdmissionStatus.discharged.displayName, "Discharged")
        XCTAssertEqual(AdmissionStatus.transferred.displayName, "Transferred")
    }
}

final class VitalsRequestTests: XCTestCase {
    
    func testDefaultStatusIsPending() {
        let r = VitalsRequest(doctorId: "d1", patientId: "p1", nurseId: "n1")
        XCTAssertEqual(r.status, .pending)
        XCTAssertNil(r.completedAt)
    }
}

final class NursePatientAssignmentTests: XCTestCase {
    
    func testAssignmentCreation() {
        let a = NursePatientAssignment(staffId: "n1", patientId: "p1")
        XCTAssertEqual(a.staffId, "n1")
        XCTAssertEqual(a.patientId, "p1")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 11. STAFF & SHIFT TESTS
// ═══════════════════════════════════════════════════════════

final class StaffTests: XCTestCase {
    
    func testDefaultsNurseMorningActive() {
        let s = Staff(name: "Nurse Priya")
        XCTAssertEqual(s.role, .nurse)
        XCTAssertEqual(s.shift, .morning)
        XCTAssertTrue(s.isActive)
    }
    
    func testWithCustomRoleAndShift() {
        let s = Staff(name: "Lab Tech", role: .labTechnician, shift: .night, qualifications: "BSc MLT")
        XCTAssertEqual(s.role, .labTechnician)
        XCTAssertEqual(s.shift, .night)
        XCTAssertEqual(s.qualifications, "BSc MLT")
    }
    
    func testCodableRoundTrip() throws {
        let s = Staff(name: "A", role: .pharmacist, shift: .evening)
        let data = try JSONEncoder().encode(s)
        let decoded = try JSONDecoder().decode(Staff.self, from: data)
        XCTAssertEqual(decoded.name, "A")
        XCTAssertEqual(decoded.role, .pharmacist)
        XCTAssertEqual(decoded.shift, .evening)
    }
}

final class ShiftTypeTests: XCTestCase {
    
    func test3Shifts() {
        XCTAssertEqual(ShiftType.allCases.count, 3)
    }
    
    func testTimeRanges() {
        XCTAssertEqual(ShiftType.morning.timeRange, "6:00 AM – 2:00 PM")
        XCTAssertEqual(ShiftType.evening.timeRange, "2:00 PM – 10:00 PM")
        XCTAssertEqual(ShiftType.night.timeRange, "10:00 PM – 6:00 AM")
    }
    
    func testIcons() {
        XCTAssertEqual(ShiftType.morning.icon, "sun.max.fill")
        XCTAssertEqual(ShiftType.evening.icon, "sun.haze.fill")
        XCTAssertEqual(ShiftType.night.icon, "moon.fill")
    }
}

final class ShiftTests: XCTestCase {
    
    func testShiftCreationDefaults() {
        let s = Shift(staffId: "s1")
        XCTAssertEqual(s.staffId, "s1")
        XCTAssertEqual(s.shiftType, .morning)
        XCTAssertTrue(s.notes.isEmpty)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 12. NOTIFICATION TESTS
// ═══════════════════════════════════════════════════════════

final class MedNexNotificationTests: XCTestCase {
    
    func testDefaultTypeIsGeneralUnread() {
        let n = MedNexNotification(userId: "u1", title: "Test", body: "Hello")
        XCTAssertEqual(n.type, .general)
        XCTAssertFalse(n.isRead)
        XCTAssertNil(n.relatedId)
    }
    
    func testCodableRoundTrip() throws {
        let n = MedNexNotification(userId: "u1", type: .prescriptionReady, title: "Rx", body: "Ready", relatedId: "rx-1")
        let data = try JSONEncoder().encode(n)
        let decoded = try JSONDecoder().decode(MedNexNotification.self, from: data)
        XCTAssertEqual(decoded.type, .prescriptionReady)
        XCTAssertEqual(decoded.relatedId, "rx-1")
    }
}

final class NotificationTypeTests: XCTestCase {
    
    func test9Types() {
        XCTAssertEqual(NotificationType.allCases.count, 9)
    }
    
    func testAllHaveNonEmptyIcons() {
        for t in NotificationType.allCases { XCTAssertFalse(t.icon.isEmpty) }
    }
    
    func testCodableRawValues() {
        XCTAssertEqual(NotificationType.appointmentBooked.rawValue, "appointment_booked")
        XCTAssertEqual(NotificationType.labResultReady.rawValue, "lab_result_ready")
        XCTAssertEqual(NotificationType.prescriptionReady.rawValue, "prescription_ready")
        XCTAssertEqual(NotificationType.shiftAssigned.rawValue, "shift_assigned")
        XCTAssertEqual(NotificationType.general.rawValue, "general")
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 13. CHAT & URGENCY TESTS
// ═══════════════════════════════════════════════════════════

final class ChatSessionTests: XCTestCase {
    
    func testEmptySessionCreation() {
        let s = ChatSession(patientId: "p1")
        XCTAssertEqual(s.patientId, "p1")
        XCTAssertTrue(s.messages.isEmpty)
    }
}

final class ChatMessageTests: XCTestCase {
    
    func testUserMessageCreation() {
        let m = ChatMessage(role: .user, content: "I have a headache")
        XCTAssertEqual(m.role, .user)
        XCTAssertEqual(m.content, "I have a headache")
        XCTAssertNil(m.suggestedSpecialty)
        XCTAssertNil(m.urgencyLevel)
    }
    
    func testAssistantMessageWithSpecialtySuggestion() {
        let m = ChatMessage(role: .assistant, content: "See a neurologist", suggestedSpecialty: .neurology, urgencyLevel: .moderate)
        XCTAssertEqual(m.role, .assistant)
        XCTAssertEqual(m.suggestedSpecialty, .neurology)
        XCTAssertEqual(m.urgencyLevel, .moderate)
    }
}

final class ChatRoleTests: XCTestCase {
    
    func testRawValues() {
        XCTAssertEqual(ChatRole.user.rawValue, "user")
        XCTAssertEqual(ChatRole.assistant.rawValue, "assistant")
        XCTAssertEqual(ChatRole.system.rawValue, "system")
    }
}

final class UrgencyLevelTests: XCTestCase {
    
    func test4Levels() {
        XCTAssertEqual(UrgencyLevel.allCases.count, 4)
    }
    
    func testDisplayNamesCapitalized() {
        XCTAssertEqual(UrgencyLevel.low.displayName, "Low")
        XCTAssertEqual(UrgencyLevel.moderate.displayName, "Moderate")
        XCTAssertEqual(UrgencyLevel.high.displayName, "High")
        XCTAssertEqual(UrgencyLevel.emergency.displayName, "Emergency")
    }
    
    func testAllHaveColorHexCodes() {
        for u in UrgencyLevel.allCases { XCTAssertEqual(u.color.count, 6) }
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 14. DEPARTMENT & DOCUMENT TESTS
// ═══════════════════════════════════════════════════════════

final class DepartmentTests: XCTestCase {
    
    func testCreationDefaults() {
        let d = Department(name: "Cardiology")
        XCTAssertEqual(d.name, "Cardiology")
        XCTAssertEqual(d.staffCount, 0)
        XCTAssertTrue(d.isActive)
        XCTAssertNil(d.headDoctorId)
    }
    
    func testWithDetails() {
        let d = Department(name: "ICU", headDoctorId: "d1", headDoctorName: "Dr. A", staffCount: 20, location: "Building A")
        XCTAssertEqual(d.headDoctorName, "Dr. A")
        XCTAssertEqual(d.staffCount, 20)
    }
}

final class PatientDocumentTests: XCTestCase {
    
    func testNamePropertyEqualsFileName() {
        let d = PatientDocument(patientId: "p1", fileName: "report.pdf", filePath: "/docs/report.pdf")
        XCTAssertEqual(d.name, "report.pdf")
        XCTAssertEqual(d.name, d.fileName)
    }
    
    func testDefaultOptionalFieldsNil() {
        let d = PatientDocument(patientId: "p1", fileName: "test.pdf", filePath: "/test")
        XCTAssertNil(d.contentType)
        XCTAssertNil(d.fileSize)
    }
    
    func testWithAllFields() {
        let d = PatientDocument(patientId: "p1", fileName: "lab.pdf", filePath: "/lab", publicUrl: "https://example.com/lab.pdf", contentType: "application/pdf", fileSize: 1024)
        XCTAssertEqual(d.publicUrl, "https://example.com/lab.pdf")
        XCTAssertEqual(d.contentType, "application/pdf")
        XCTAssertEqual(d.fileSize, 1024)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 15. DATE EXTENSION TESTS
// ═══════════════════════════════════════════════════════════

final class DateExtensionTests: XCTestCase {
    
    func testIsTodayReturnsTrueForNow() {
        XCTAssertTrue(Date().isToday)
    }
    
    func testIsTodayReturnsFalseForYesterday() {
        let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: Date())!
        XCTAssertFalse(yesterday.isToday)
    }
    
    func testIsTomorrowReturnsTrue() {
        let tomorrow = Calendar.current.date(byAdding: .day, value: 1, to: Date())!
        XCTAssertTrue(tomorrow.isTomorrow)
    }
    
    func testIsTomorrowReturnsFalseForToday() {
        XCTAssertFalse(Date().isTomorrow)
    }
    
    func testIsPastReturnsTrueForYesterday() {
        let yesterday = Calendar.current.date(byAdding: .day, value: -1, to: Date())!
        XCTAssertTrue(yesterday.isPast)
    }
    
    func testIsPastReturnsFalseForFuture() {
        let tomorrow = Calendar.current.date(byAdding: .day, value: 1, to: Date())!
        XCTAssertFalse(tomorrow.isPast)
    }
    
    func testAddingDaysWorks() {
        let today = Date()
        let inThreeDays = today.adding(days: 3)
        let diff = Calendar.current.dateComponents([.day], from: today, to: inThreeDays).day ?? 0
        XCTAssertEqual(diff, 3)
    }
    
    func testAddingHoursWorks() {
        let now = Date()
        let inFiveHours = now.adding(hours: 5)
        let diff = Calendar.current.dateComponents([.hour], from: now, to: inFiveHours).hour ?? 0
        XCTAssertEqual(diff, 5)
    }
    
    func testShortDateIsNonEmpty() {
        XCTAssertFalse(Date().shortDate.isEmpty)
    }
    
    func testMedicalFormatIsNonEmpty() {
        XCTAssertFalse(Date().medicalFormat.isEmpty)
    }
    
    func testTimeOnlyIsNonEmpty() {
        XCTAssertFalse(Date().timeOnly.isEmpty)
    }
    
    func testDayOfWeekIsNonEmpty() {
        XCTAssertFalse(Date().dayOfWeek.isEmpty)
    }
    
    func testRelativeIsNonEmpty() {
        XCTAssertFalse(Date().relative.isEmpty)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - 16. DATA INTEGRITY & ENUM COUNT TESTS
// ═══════════════════════════════════════════════════════════

final class DataIntegrityTests: XCTestCase {
    
    func testAppointmentStatusCount() { XCTAssertEqual(AppointmentStatus.allCases.count, 5) }
    func testAppointmentTypeCount() { XCTAssertEqual(AppointmentType.allCases.count, 5) }
    func testBillStatusCount() { XCTAssertEqual(BillStatus.allCases.count, 5) }
    func testBillItemCategoryCount() { XCTAssertEqual(BillItemCategory.allCases.count, 6) }
    func testPaymentModeCount() { XCTAssertEqual(PaymentMode.allCases.count, 5) }
    func testUserRoleCount() { XCTAssertEqual(UserRole.allCases.count, 8) }
    func testNotificationTypeCount() { XCTAssertEqual(NotificationType.allCases.count, 9) }
    func testMedicalSpecialtyCount() { XCTAssertEqual(MedicalSpecialty.allCases.count, 18) }
    func testLabTestCategoryCount() { XCTAssertEqual(LabTestCategory.allCases.count, 9) }
    func testLabTestStatusCount() { XCTAssertEqual(LabTestStatus.allCases.count, 5) }
    func testLabTestPriorityCount() { XCTAssertEqual(LabTestPriority.allCases.count, 3) }
    func testShiftTypeCount() { XCTAssertEqual(ShiftType.allCases.count, 3) }
    func testGenderCount() { XCTAssertEqual(Gender.allCases.count, 3) }
    func testBloodTypeCount() { XCTAssertEqual(BloodType.allCases.count, 9) }
    func testUrgencyLevelCount() { XCTAssertEqual(UrgencyLevel.allCases.count, 4) }
    func testMedicineFrequencyCount() { XCTAssertEqual(MedicineFrequency.allCases.count, 9) }
    func testAdmissionStatusCount() { XCTAssertEqual(AdmissionStatus.allCases.count, 3) }
    func testInventoryCategoryCount() { XCTAssertEqual(InventoryCategory.allCases.count, 6) }
    func testVitalsRequestStatusCount() { XCTAssertEqual(VitalsRequestStatus.allCases.count, 2) }
}
